FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY . .

# CRITICAL FIX: Go inside the folder first!
WORKDIR /app/backend/auth-service
RUN go mod download
RUN go build -o /server main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /server .
EXPOSE 8083
CMD ["./server"]