FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY . .
RUN go mod download
# Hardcoded path for Auth Service
RUN go build -o server ./backend/auth-service

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/server .
EXPOSE 8083
CMD ["./server"]