FROM golang:1.25alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY . .

# CRITICAL FIX: Go inside the folder first!
WORKDIR /app/backend/api-gateway
RUN go mod download
RUN go build -o /server main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /server .
EXPOSE 8080
CMD ["./server"]

