FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY . .
RUN go mod download
# Hardcoded path for Webhook Service
RUN go build -o server ./backend/webhook-service

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/server .
EXPOSE 8082
CMD ["./server"]